[package]
name = "limlog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
positioned-io = "0.3.1"
bincode = "1.3"
bitflags = "1.3"
bytes = "1.4"
serde = { version = "1", features = ["derive"] }
anyhow = "1"
thiserror = "1.0"
crossbeam-queue = "0.3"
kanal = { version = "0.1.0-pre8", default-features = false }
smallvec = { version = "1.10", features = ["union", "const_new", "const_generics", "specialization"] }

[dev-dependencies]
criterion = "0.4.0"

[profile.release]
debug = true

[[bench]]
name = "appender_benchmark"
harness = false
