[package]
name = "limlog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
positioned-io = "0.3.1"
bincode = "1.3"
bitflags = "1.3"
serde = { version = "1", features = ["derive"] }
crossbeam = "0.8"
anyhow = "1"
once_cell = "1.17"
